import {useEffect, useRef, useState, type FormEvent} from 'react';
import {ArrowLeft, Bot, FileText, Headphones, MicOff, Paperclip, Send, ShieldCheck, Sparkles, X} from 'lucide-react';

type Props={lang:'en'|'ta';onClose:()=>void};
type Turn={role:'user'|'assistant';content:string};
const copy={en:{back:'Back to SakhiCare',title:'Talk with Sakhi',subtitle:'Ask about PMMVY or share a document for help.',welcome:'Hello, Iâ€™m Sakhi. I can explain the PMMVY steps in simple language. What would you like help with?',placeholder:'Message Sakhiâ€¦',send:'Send message',attach:'Attach a file',voice:'Start live voice',end:'End voice',listening:'Live voice is on. Speak naturally; you can interrupt anytime.',ready:'Your private conversation',disclaimer:'SakhiCare guidance only Â· Confirm details on the official portal',fileHint:'PDF, image, Word, text or spreadsheet Â· Up to 10 MB each',error:'Could not send that. Please try again.',config:'AI chat needs an OpenAI API key configured on the server.',you:'You',sakhi:'Sakhi'},ta:{back:'SakhiCare-à®•à¯à®•à¯à®¤à¯ à®¤à®¿à®°à¯à®®à¯à®ªà¯',title:'à®šà®•à®¿à®¯à¯à®Ÿà®©à¯ à®ªà¯‡à®šà¯à®™à¯à®•à®³à¯',subtitle:'PMMVY à®ªà®±à¯à®±à®¿ à®•à¯‡à®³à¯à®™à¯à®•à®³à¯ à®…à®²à¯à®²à®¤à¯ à®†à®µà®£ à®‰à®¤à®µà®¿ à®ªà¯†à®±à¯à®™à¯à®•à®³à¯.',welcome:'à®µà®£à®•à¯à®•à®®à¯, à®¨à®¾à®©à¯ à®šà®•à®¿. PMMVY à®ªà®Ÿà®¿à®•à®³à¯ˆ à®Žà®³à®¿à®¯ à®®à¯Šà®´à®¿à®¯à®¿à®²à¯ à®µà®¿à®³à®•à¯à®•à¯à®µà¯‡à®©à¯. à®‰à®™à¯à®•à®³à¯à®•à¯à®•à¯ à®Žà®©à¯à®© à®‰à®¤à®µà®¿ à®µà¯‡à®£à¯à®Ÿà¯à®®à¯?',placeholder:'à®šà®•à®¿à®¯à®¿à®Ÿà®®à¯ à®šà¯†à®¯à¯à®¤à®¿â€¦',send:'à®šà¯†à®¯à¯à®¤à®¿ à®…à®©à¯à®ªà¯à®ªà¯',attach:'à®•à¯‹à®ªà¯à®ªà¯ˆ à®‡à®£à¯ˆ',voice:'à®¨à¯‡à®°à®²à¯ˆ à®•à¯à®°à®²à¯ˆà®¤à¯ à®¤à¯Šà®Ÿà®™à¯à®•à¯',end:'à®•à¯à®°à®²à¯ˆ à®¨à®¿à®±à¯à®¤à¯à®¤à¯',listening:'à®¨à¯‡à®°à®²à¯ˆ à®•à¯à®°à®²à¯ à®‡à®¯à®™à¯à®•à¯à®•à®¿à®±à®¤à¯. à®‡à®¯à®²à¯à®ªà®¾à®•à®ªà¯ à®ªà¯‡à®šà¯à®™à¯à®•à®³à¯.',ready:'à®‰à®™à¯à®•à®³à¯ à®‰à®°à¯ˆà®¯à®¾à®Ÿà®²à¯',disclaimer:'SakhiCare à®µà®´à®¿à®•à®¾à®Ÿà¯à®Ÿà®²à¯ à®®à®Ÿà¯à®Ÿà¯à®®à¯‡ Â· à®…à®¤à®¿à®•à®¾à®°à®ªà¯à®ªà¯‚à®°à¯à®µ à®¤à®³à®¤à¯à®¤à®¿à®²à¯ à®‰à®±à¯à®¤à®¿à®ªà¯à®ªà®Ÿà¯à®¤à¯à®¤à®µà¯à®®à¯',fileHint:'PDF, à®ªà®Ÿà®®à¯, Word, à®‰à®°à¯ˆ à®…à®²à¯à®²à®¤à¯ spreadsheet Â· à®’à®µà¯à®µà¯Šà®©à¯à®±à¯à®®à¯ 10 MB à®µà®°à¯ˆ',error:'à®…à®©à¯à®ªà¯à®ª à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ. à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®®à¯à®¯à®±à¯à®šà®¿à®•à¯à®•à®µà¯à®®à¯.',config:'à®šà¯‡à®µà¯ˆà®¯à®•à®¤à¯à®¤à®¿à®²à¯ OpenAI API à®µà®¿à®šà¯ˆ à®¤à¯‡à®µà¯ˆ.',you:'à®¨à¯€à®™à¯à®•à®³à¯',sakhi:'à®šà®•à®¿'}};
const api=(import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8000')+'/api/openai';
export default function SakhiChat({lang,onClose}:Props){
 const t=copy[lang], [turns,setTurns]=useState<Turn[]>([]),[draft,setDraft]=useState(''),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[live,setLive]=useState(false),[error,setError]=useState('');
 const turnsRef=useRef<Turn[]>([]),contextFilesRef=useRef<File[]>([]),dcRef=useRef<RTCDataChannel|null>(null),pcRef=useRef<RTCPeerConnection|null>(null),streamRef=useRef<MediaStream|null>(null),audioRef=useRef<HTMLAudioElement|null>(null),bottomRef=useRef<HTMLDivElement|null>(null);
 const add=(turn:Turn)=>{turnsRef.current=[...turnsRef.current,turn];setTurns(turnsRef.current)};
 useEffect(()=>{if(typeof bottomRef.current?.scrollIntoView==='function')bottomRef.current.scrollIntoView({behavior:'smooth'})},[turns,busy]);
 const stop=()=>{try{dcRef.current?.send(JSON.stringify({type:'session.close'}))}catch{};dcRef.current?.close();pcRef.current?.close();streamRef.current?.getTracks().forEach(x=>x.stop());if(audioRef.current)audioRef.current.srcObject=null;dcRef.current=null;pcRef.current=null;streamRef.current=null;setLive(false)};
 useEffect(()=>()=>stop(),[]);
 const start=async()=>{setError('');setBusy(true);try{
   const form=new FormData();form.set('language',lang==='ta'?'Tamil':'English');const tokenRes=await fetch(api+'/realtime-token',{method:'POST',body:form});const token=await tokenRes.json();if(!tokenRes.ok)throw new Error(token.detail||t.error);
   const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;
   const pc=new RTCPeerConnection();pcRef.current=pc;stream.getTracks().forEach(track=>pc.addTrack(track,stream));
   const audio=new Audio();audio.autoplay=true;audioRef.current=audio;pc.ontrack=e=>{audio.srcObject=e.streams[0]};
   const dc=pc.createDataChannel('oai-events');dcRef.current=dc;dc.onmessage=e=>{try{const event=JSON.parse(e.data);if(event.type==='conversation.item.input_audio_transcription.completed'&&event.transcript)add({role:'user',content:event.transcript});if(event.type==='response.output_audio_transcript.done'&&event.transcript)add({role:'assistant',content:event.transcript});if(event.type==='response.output_text.done'&&event.text&&!turnsRef.current[turnsRef.current.length-1]?.content.includes(event.text))add({role:'assistant',content:event.text})}catch{}};
   const offer=await pc.createOffer();await pc.setLocalDescription(offer);const response=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:`Bearer ${token.value}`,'Content-Type':'application/sdp'},body:offer.sdp});if(!response.ok)throw new Error(t.error);await pc.setRemoteDescription({type:'answer',sdp:await response.text()});setLive(true);
  }catch(e){stop();setError(e instanceof Error?e.message:t.error)}finally{setBusy(false)}};
 const submit=async(e?:FormEvent)=>{e?.preventDefault();if(!draft.trim()&&!files.length)return;const message=draft.trim()||'Please help me understand the attached file.';const selected=[...files],attachments=selected.length?[...contextFilesRef.current,...selected].slice(-4):contextFilesRef.current,previous=turnsRef.current.slice(-12);setDraft('');setFiles([]);setError('');add({role:'user',content:message+(selected.length?`  Â·  ${selected.map(f=>f.name).join(', ')}`:'')});
  if(live&&dcRef.current?.readyState==='open'&&!selected.length){dcRef.current.send(JSON.stringify({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text:message}]}}));dcRef.current.send(JSON.stringify({type:'response.create'}));return}
  setBusy(true);try{const form=new FormData();form.set('message',message);form.set('history',JSON.stringify(previous));attachments.forEach(f=>form.append('files',f));const res=await fetch(api+'/chat',{method:'POST',body:form});const data=await res.json();if(!res.ok)throw new Error(data.detail||t.error);contextFilesRef.current=attachments;add({role:'assistant',content:data.reply})}catch(e){setError(e instanceof Error?e.message:t.error)}finally{setBusy(false)}};
 const addFiles=(incoming:FileList|null)=>{if(!incoming)return;const picked=Array.from(incoming);const valid=picked.filter(f=>f.size<=10*1024*1024);setFiles(old=>[...old,...valid].slice(0,4));if(valid.length<picked.length)setError('Each file must be under 10 MB.')};
 return <section className="sakhiChat" aria-label={t.title}>
  <header className="chatTop"><button className="chatBack" onClick={onClose}><ArrowLeft size={18}/>{t.back}</button><div className="chatIdentity"><span className="chatAvatar"><Sparkles size={18}/></span><div><strong>{t.title}</strong><small><span className={live?'chatLiveDot':''}/>{live?t.listening:t.ready}</small></div></div><span className="chatMark">SAKHISETU</span></header>
  <div className="chatTranscript" aria-live="polite">{turns.length===0&&<div className="chatWelcome"><div className="chatWelcomeVisual" aria-hidden="true"><i className="chatWelcomeHalo"/><i className="chatWelcomeSun"/><span className="chatWelcomeFlower">✿</span><span className="chatWelcomeBot"><Bot size={25}/></span></div><span className="chatWelcomeTag"><Sparkles size={13}/> VISUAL · VOICE · TEXT</span><h1>{t.welcome}</h1><p>{t.subtitle}</p><div className="chatQuickPrompts"><button type="button" onClick={()=>setDraft('What is PMMVY?')}>What is PMMVY?</button><button type="button" onClick={()=>setDraft('What documents should I prepare?')}>Documents to prepare</button><button type="button" onClick={()=>setDraft('Explain it in simple steps')}>Explain in simple steps</button></div></div>}{turns.map((turn,i)=><article className={'chatMessage '+turn.role} key={i}><span className="messageAvatar">{turn.role==='user'?t.you:t.sakhi}</span><p>{turn.content}</p></article>)}{busy&&<div className="chatTyping"><i/><i/><i/></div>}<div ref={bottomRef}/></div>
  <form className="chatComposerWrap" onSubmit={submit}><div className="chatComposer"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void submit()}}} placeholder={t.placeholder} aria-label={t.placeholder} disabled={busy}/><div className="composerTools"><label className="attachButton" title={t.attach}><Paperclip size={18}/><input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.md,.csv,.json,.docx,.rtf,.xlsx,.pptx" onChange={e=>{addFiles(e.target.files);e.currentTarget.value=''}} aria-label={t.attach}/></label><button type="button" className={'liveButton '+(live?'active':'')} onClick={()=>live?stop():void start()} disabled={busy} aria-label={live?t.end:t.voice}>{live?<MicOff size={18}/>:<Headphones size={18}/>}<span>{live?t.end:t.voice}</span></button><button className="sendButton" type="submit" disabled={busy||(!draft.trim()&&!files.length)} aria-label={t.send}><Send size={18}/></button></div></div>{files.length>0&&<div className="fileChips">{files.map((f,i)=><span key={`${f.name}-${i}`}><FileText size={14}/>{f.name}<button type="button" onClick={()=>setFiles(old=>old.filter((_,j)=>i!==j))} aria-label={`Remove ${f.name}`}><X size={13}/></button></span>)}</div>}<div className="chatMeta"><span><ShieldCheck size={13}/>{t.disclaimer}</span><small>{t.fileHint}</small></div>{error&&<p className="chatError" role="alert">{error}</p>}</form>
 </section>
}
