import {useEffect, useRef, useState} from 'react';
import {Mic, MicOff, Volume2, LoaderCircle} from 'lucide-react';
type Props={lang:'en'|'ta';onIntent?:(answer:'yes'|'no')=>void};
const names:Record<string,string>={en:'English',hi:'à¤¹à¤¿à¤¨à¥à¤¦à¥€',ta:'à®¤à®®à®¿à®´à¯',te:'à°¤à±†à°²à±à°—à±',bn:'à¦¬à¦¾à¦‚à¦²à¦¾',kn:'à²•à²¨à³à²¨à²¡',ml:'à´®à´²à´¯à´¾à´³à´‚',mr:'à¤®à¤°à¤¾à¤ à¥€',gu:'àª—à«àªœàª°àª¾àª¤à«€',pa:'à¨ªà©°à¨œà¨¾à¨¬à©€',ur:'Ø§Ø±Ø¯Ùˆ',or:'à¬“à¬¡à¬¼à¬¿à¬†',as:'à¦…à¦¸à¦®à§€à¦¯à¦¼à¦¾',ne:'à¤¨à¥‡à¤ªà¤¾à¤²à¥€'};
const copy={en:{talk:'Speak in your language',stop:'Tap to finish',listening:'Listeningâ€¦',working:'Understanding your voiceâ€¦',repeat:'Please speak once more, a little more slowly.',unavailable:'Microphone or voice service is unavailable. Use the buttons instead.',noVoice:'A voice reply is not available in this language on this device. The reply is shown as text.',heard:'I heard',reply:'A reply for you',},ta:{talk:'à®‰à®™à¯à®•à®³à¯ à®®à¯Šà®´à®¿à®¯à®¿à®²à¯ à®ªà¯‡à®šà¯à®™à¯à®•à®³à¯',stop:'à®®à¯à®Ÿà®¿à®•à¯à®•à®¤à¯ à®¤à¯Šà®Ÿà®µà¯à®®à¯',listening:'à®•à¯‡à®Ÿà¯à®•à®¿à®±à®¤à¯â€¦',working:'à®‰à®™à¯à®•à®³à¯ à®•à¯à®°à®²à¯ˆà®ªà¯ à®ªà¯à®°à®¿à®¨à¯à®¤à¯à®•à¯Šà®³à¯à®•à®¿à®±à¯‹à®®à¯â€¦',repeat:'à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®•à¯Šà®žà¯à®šà®®à¯ à®®à¯†à®¤à¯à®µà®¾à®•à®ªà¯ à®ªà¯‡à®šà¯à®™à¯à®•à®³à¯.',unavailable:'à®’à®²à®¿à®µà®¾à®™à¯à®•à®¿ à®…à®²à¯à®²à®¤à¯ à®•à¯à®°à®²à¯ à®šà¯‡à®µà¯ˆ à®‡à®²à¯à®²à¯ˆ. à®ªà¯Šà®¤à¯à®¤à®¾à®©à¯à®•à®³à¯ˆà®ªà¯ à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à¯à®™à¯à®•à®³à¯.',noVoice:'à®‡à®¨à¯à®¤ à®®à¯Šà®´à®¿à®¯à®¿à®²à¯ à®•à¯à®°à®²à¯ à®ªà®¤à®¿à®²à¯ à®‡à®²à¯à®²à¯ˆ. à®ªà®¤à®¿à®²à¯ à®Žà®´à¯à®¤à¯à®¤à®¾à®•à®•à¯ à®•à®¾à®Ÿà¯à®Ÿà®ªà¯à®ªà®Ÿà¯à®•à®¿à®±à®¤à¯.',heard:'à®¨à®¾à®©à¯ à®•à¯‡à®Ÿà¯à®Ÿà®¤à¯',reply:'à®‰à®™à¯à®•à®³à¯à®•à¯à®•à®¾à®© à®ªà®¤à®¿à®²à¯'}};
export default function VoiceAssistant({lang,onIntent}:Props){const [recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[transcript,setTranscript]=useState(''),[reply,setReply]=useState(''),[detected,setDetected]=useState(''),[message,setMessage]=useState(''),[voiceReply,setVoiceReply]=useState(false);const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number|undefined>(undefined),audio=useRef<HTMLAudioElement|null>(null),t=copy[lang];
 useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current);recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());audio.current?.pause()},[]);
 async function process(blob:Blob){setBusy(true);setMessage('');setTranscript('');setReply('');setVoiceReply(false);try{const form=new FormData();form.append('audio',blob,'voice.webm');const base=import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8000';const response=await fetch(base+'/api/voice/chat',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.detail||t.unavailable);if(data.needs_repeat){setDetected(data.language||'');setMessage(t.repeat);return}setDetected(data.language||'');setTranscript(data.transcript||'');if(data.intent&&onIntent)onIntent(data.intent);if(data.reply){setReply(data.reply);try{const speech=await fetch(base+'/api/voice/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:data.reply,language:data.language})});if(speech.ok){const url=URL.createObjectURL(await speech.blob());const player=new Audio(url);audio.current=player;await player.play();setVoiceReply(true);player.onended=()=>URL.revokeObjectURL(url)}else speakLocally(data.reply,data.language)}catch{speakLocally(data.reply,data.language)}}else setMessage(t.noVoice)}catch(e){const detail=e instanceof Error?e.message:'';setMessage(detail.includes('Failed to fetch')||detail.includes('NetworkError')?t.unavailable:detail||t.unavailable)}finally{setBusy(false)}}
 function speakLocally(text:string,language:string){if(!('speechSynthesis'in window)){setMessage(t.noVoice);return}const voices=window.speechSynthesis.getVoices();const voice=voices.find(item=>item.lang.toLowerCase().startsWith(language.toLowerCase()));if(!voice){setMessage(t.noVoice);return}const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=voice.lang;utterance.onerror=()=>setMessage(t.noVoice);window.speechSynthesis.speak(utterance);setVoiceReply(true)}
 async function toggle(){if(recording){if(timer.current)window.clearTimeout(timer.current);recorder.current?.stop();setRecording(false);return}try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('unavailable');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream.current);recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onerror=()=>setMessage(t.unavailable);rec.onstop=()=>{stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});if(blob.size)void process(blob);else setMessage(t.repeat)};rec.start();setRecording(true);setMessage(t.listening);timer.current=window.setTimeout(()=>{if(rec.state==='recording'){rec.stop();setRecording(false)}},7000)}catch{setRecording(false);setMessage(t.unavailable)}}
 return <div className="voiceAssistant"><button className={'voiceAssistantButton '+(recording?'recording':'')} onClick={()=>void toggle()} aria-label={recording?t.stop:t.talk} aria-pressed={recording}>{busy?<LoaderCircle className="spin" size={18}/>:recording?<MicOff size={18}/>:<Mic size={18}/>}<span>{busy?t.working:recording?t.stop:t.talk}</span><span className="voicePulse" aria-hidden="true"/></button>{(transcript||reply||message)&&<div className="voiceResult" aria-live="polite" dir={['ar','ur','he','fa'].includes(detected)?'rtl':'auto'}>{detected&&<div className="detectedLanguage">{names[detected]||detected}</div>}{transcript&&<p><b>{t.heard}:</b> {transcript}</p>}{reply&&<p><b>{t.reply}:</b> {reply} {voiceReply&&<Volume2 size={15} aria-label="Voice reply played"/>}</p>}{message&&<p>{message}</p>}</div>}</div>
}
