// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import App from './App';

afterEach(()=>{cleanup();localStorage.clear()});
function clearFirstVisit(){const skip=screen.getAllByRole('button',{name:/skip guide/i})[0];if(skip)fireEvent.click(skip)}
function begin(){render(<App/>);clearFirstVisit();fireEvent.click(screen.getByRole('button',{name:/begin/i}));}
describe('SakhiCare guided journey',()=>{
 it('automatically opens the guide on a first visit and remembers skip',()=>{render(<App/>);expect(screen.getByRole('dialog')).toBeInTheDocument();fireEvent.click(screen.getAllByRole('button',{name:/skip guide/i})[0]);expect(localStorage.getItem('sakhisetu_onboarding_completed')).toBe('true');expect(screen.queryByRole('dialog')).not.toBeInTheDocument()});
 it('changes the language selector',()=>{render(<App/>);clearFirstVisit();const start=screen.getByRole('button',{name:/begin/i}).textContent;fireEvent.click(screen.getByRole('button',{name:/select language/i}));expect(screen.getAllByRole('button')[2].textContent).not.toBe(start)});
 it('moves one question at a time with touch answers',()=>{begin();expect(screen.getByText(/currently pregnant/i)).toBeInTheDocument();fireEvent.click(screen.getAllByRole('button',{name:/yes/i})[0]);expect(screen.getByText(/first child/i)).toBeInTheDocument()});
 it('offers touch controls as a camera-independent fallback',()=>{begin();expect(screen.getAllByRole('button',{name:/yes/i})[0]).toBeInTheDocument();expect(screen.getAllByRole('button',{name:/no/i})[0]).toBeInTheDocument()});
 it('opens the help explanation',()=>{begin();fireEvent.click(screen.getByRole('button',{name:/^Help$/i}));expect(screen.getByRole('dialog')).toBeInTheDocument()});
 it('keeps touch controls available when camera access is unavailable',async()=>{begin();fireEvent.click(screen.getByRole('button',{name:/turn on/i}));await waitFor(()=>expect(screen.getAllByRole('button',{name:/yes/i})[0]).toBeInTheDocument())});
 it('keeps touch available when microphone capture is unsupported',()=>{begin();fireEvent.click(screen.getByRole('button',{name:/speak in your language/i}));expect(screen.getAllByRole('button',{name:/yes/i})[0]).toBeInTheDocument()});
 it('renders a guidance result after three answers',()=>{begin();fireEvent.click(screen.getAllByRole('button',{name:/yes/i})[0]);fireEvent.click(screen.getAllByRole('button',{name:/no/i})[0]);fireEvent.click(screen.getAllByRole('button',{name:/yes/i})[0]);expect(screen.getByText(/not an eligibility decision/i)).toBeInTheDocument()});
 it('completes checklist and official portal handoff with confirmation',()=>{const open=vi.spyOn(window,'open').mockImplementation(()=>null);begin();fireEvent.click(screen.getAllByRole('button',{name:/yes/i})[0]);fireEvent.click(screen.getAllByRole('button',{name:/no/i})[0]);fireEvent.click(screen.getAllByRole('button',{name:/yes/i})[0]);fireEvent.click(screen.getByRole('button',{name:/show my checklist/i}));fireEvent.click(screen.getByRole('button',{name:/what is this/i}));fireEvent.click(screen.getByRole('button',{name:/open official application/i}));expect(screen.getByText(/leaving sakhicare/i)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/continue to portal/i}));expect(open).toHaveBeenCalledWith('https://pmmvy.wcd.gov.in/','_blank','noopener,noreferrer');expect(screen.getByRole('link',{name:/open official portal/i})).toHaveAttribute('href','https://pmmvy.wcd.gov.in/');open.mockRestore()});
 it('shows the replay guide and advances its visual steps',()=>{render(<App/>);clearFirstVisit();fireEvent.click(screen.getByRole('button',{name:/replay guide/i}));expect(screen.getByRole('dialog')).toBeInTheDocument();expect(screen.getByText(/tap the green button to begin/i)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/next/i}));expect(screen.getByText(/tap yes or no for each question/i)).toBeInTheDocument()});
 it('shows an animated browser microphone Allow example in the guide',async()=>{render(<App/>);clearFirstVisit();fireEvent.click(screen.getByRole('button',{name:/replay guide/i}));for(let i=2;i<=4;i++){fireEvent.click(document.querySelector<HTMLButtonElement>('.followCard .guideNext')!);await waitFor(()=>expect(screen.getByRole('dialog')).toHaveTextContent(`${i}/43`))}expect(screen.getByRole('dialog').textContent).toMatch(/Allow for the microphone/i);expect(screen.getByText(/this site wants to use your microphone/i)).toBeInTheDocument();expect(screen.getByText('Allow')).toBeInTheDocument();expect(screen.getByText(/Allow in the browser/i)).toBeInTheDocument()});
 it('opens the themed Sakhi chat with text, voice, attachments and suggested prompts',()=>{render(<App/>);clearFirstVisit();fireEvent.click(screen.getByRole('button',{name:/talk with sakhi/i}));expect(screen.getByRole('region',{name:/talk with sakhi/i})).toBeInTheDocument();expect(screen.getByText(/visual · voice · text/i)).toBeInTheDocument();expect(screen.getByRole('textbox',{name:/message sakhi/i})).toBeInTheDocument();expect(screen.getByRole('button',{name:/start live voice/i})).toBeInTheDocument();expect(screen.getByLabelText(/attach a file/i)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/what is pmmvy/i}));expect(screen.getByRole('textbox',{name:/message sakhi/i})).toHaveValue('What is PMMVY?')});
});
